### ISSUE TITLE
USBToolBox.kext not loading (Mojave) - "library kext com.apple.kpi.bsd not compatible with requested version 19.0.0"

### ISSUE THREAD

**Issue by WWWFWWW** [USBToolBox/kext#3]
Obviously, it links something from kernel 19, ie Catalina? I am on Mojave FIY.

```
Kext com.dhinakg.USBToolBox.kext - library kext com.apple.kpi.bsd not compatible with requested version 19.0.0.
localhost kernel[0]: Can't load kext com.dhinakg.USBToolBox.kext - failed to resolve library dependencies.
localhost kernel[0]: Kext com.dhinakg.USBToolBox.kext failed to load (0xdc00800e).
localhost kernel[0]: Failed to load kext com.dhinakg.USBToolBox.kext (error 0xdc00800e).
localhost kernel[0]: Couldn't alloc class "USBToolBox"
```

**Comment by dhinakg** [comment]
Can you try the build from [here](https://github.com/USBToolBox/kext/actions/runs/832067005)? Just click "Artifacts" at the bottom

**Comment by WWWFWWW** [comment]
Correct, that loads! Thanks. Getting some errors in the debug log, but IoReg devices look mostly correct. Attached the log.
[USBToolBox.txt](https://github.com/USBToolBox/kext/files/6460381/USBToolBox.txt)

Note: UHCI ports don't work. My MB is old, separate controllers for UHCI and EHCI (Intel Series 5). The only IoReg key in the USB0@1D controller is USBToolBox, there is no PRT... keys. UTBMap.kext seems correct. Might be because of my boot args? I used -utbacpioff & -utbappleoff (by mistake - I misunderstood the description, I saw the "disable" but missed the "removal" - thought it "disables existing" prior to mapping). I'll try without the args.

EHCI and XHCI ports work well.

`IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/USB0@1D/USBToolBox`:
![screen](https://user-images.githubusercontent.com/30300299/117848133-47344580-b283-11eb-8e89-32bf996d8151.jpg)

UHCI map from generated map kext looks correct:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>USB0</key>
	<dict>
		<key>CFBundleIdentifier</key>
		<string>com.dhinakg.USBToolBox.kext</string>
		<key>IOClass</key>
		<string>USBToolBox</string>
		<key>IOMatchCategory</key>
		<string>USBToolBox</string>
		<key>IONameMatch</key>
		<string>USB0</string>
		<key>IOProviderClass</key>
		<string>IOPCIDevice</string>
		<key>IOProviderMergeProperties</key>
		<dict>
			<key>port-count</key>
			<data>
			AgAAAA==
			</data>
			<key>ports</key>
			<dict>
				<key>PRT1</key>
				<dict>
					<key>#comment</key>
					<string>TopU</string>
					<key>UsbConnector</key>
					<integer>0</integer>
					<key>port</key>
					<data>
					AgAAAA==
					</data>
				</dict>
			</dict>
		</dict>
	</dict>
</dict>
</plist>
```

**Comment by dhinakg** [comment]
Hm, can you upload an IOReg?

**Comment by WWWFWWW** [comment]
It might be totally unrelated to USBToolBox, my motherboard is quite old and could well be some unrelated ACPI issues or problems with hand-off, but thanks anyway. I will try few other option combinations in Bios & OpenCore, as well as remove the UHCI ports from the custom map and disable USBTB port removal, to hopefully try & see whether the UHCI problem lies elsewhere and what the UHCI controller keys look like without the USBTB mapping.

Anyway, thanks for solving the main issue with USBTB not loading on Mojave.

**Comment by dhinakg** [comment]
I took a look at your IOReg, and I don't think there's much USBToolBox can do. The class codes for the controllers where there's no USB kext attached are correct. My best guess is that the drivers are attaching, but then detaching due to an error - could be something (driver or controller) not following spec, defective controllers, etc.

You can try adding `io=1e` to your boot args and then checking logs to see where it quits (`probe`, `start`, etc.) but I don't really think I can do anything about it.

**Comment by WWWFWWW** [comment]
Thanks. I thought it was probably unrelated to UsbToolBox, most likely bad ACPI issues with my HW. I might just try disabling the UHCI ports completely in SSDT, use an EHCI hub for any old UHCI peripherals and see if disabling it borks my POST screen keyboard use ;)

I guess we can close this one, then? The updated OSBundleLibraries test build worked fine where it could.
