### ISSUE TITLE
Bluetooth dongle

### ISSUE THREAD

**Issue by lo97** [USBToolBox/kext#4]
Hi, I'm not a developer so I don't know if it's related but since I started using this kext instead of usbinjectall, my external bluetooth dongle doesn't work anymore. I read that is because it's not seen as internal anymore, is it possible to do something about it? Thanks

**Comment by dhinakg** [comment]
That's weird, can you upload an IOReg of before using USBToolBox and an IOReg of after?

**Comment by dhinakg** [comment]
Closing as no response, please create a new issue if this still persists
