### ISSUE TITLE
Update USBToolBox Kext for Ventura.

### ISSUE THREAD

**Issue by THOMASVGTR** [USBToolBox/kext#8]
Catalina booting is alright. Up to Monterey is okay. But, booting Ventura with UTB is creating timeout issues. Developers, please upgrade and update this kext(Driver) as soon/early as possible.

**Comment by kernel-dev** [comment]
Could you provide more detailed information? I'm running macOS 13 Beta 9, and everything is working fine on my end with the latest KEXT.

**Comment by THOMASVGTR** [comment]
The issue just solved by deleting hyperV Monterey.kext which just added by me (mistakenly). After deleting that kext by booting LinuxMint from USB and clearing nvram from open core picker, my hack book pro (Ventura public stable) just booted automatically. Thanks dev for replying. You can close this issue as well. UTB kext is still amazing for mapping ports. Well done.

**Comment by AnubisGreat** [comment]
I have been trying all day with your stuff. Finally I have now a kext file prepeared under Win11. No succes with making kext file under Ventura. Before recogniction with UTBDefault.kext 4 ports do not work at all under OSX. With a file I made under WIn11 these USB3 ports seen under Win11 as USB3 are visible and work now under Ventura as USB2.:(

**Comment by kernel-dev** [comment]
You should also ensure you map companion ports in that case, as USB3.x ports have 2 personalities:

- USB 2.0 personality; and
- USB 3.0 personality.

You have to map each personality _individually_.

I could be wrong, although I do think that's how it works.

**Comment by dhinakg** [comment]
Please use forums for support, since this isn't a kext issue I'm closing this.
